export const AUDIT_ACTION = {
  INVITATION_CREATED: 'invitation.created',
  INVITATION_ACCEPTED: 'invitation.accepted',
  INVITATION_REVOKED: 'invitation.revoked',
  MEMBERSHIP_UPDATED: 'membership.updated',
  SESSION_REVOKED: 'session.revoked',
  SESSIONS_REVOKED_OTHERS: 'sessions.revoked_others',
  PROFILE_UPDATED: 'profile.updated',
  ADMIN_USER_UPDATED: 'admin.user.updated',
  LEAD_CREATED: 'lead.created',
  LEAD_UPDATED: 'lead.updated',
  LEAD_DELETED: 'lead.deleted',
  LEAD_CLAIMED: 'lead.claimed',
  LEAD_REASSIGNED: 'lead.reassigned',
  LEAD_UNASSIGNED: 'lead.unassigned',
  LEAD_STATUS_CHANGED: 'lead.status_changed',
  LEAD_NOTE_ADDED: 'lead.note_added',
  LEAD_NOTE_UPDATED: 'lead.note_updated',
  LEAD_NOTE_DELETED: 'lead.note_deleted',
  LEAD_FOLLOWUP_UPDATED: 'lead.followup_updated',
  LEAD_CONVERTED: 'lead.converted',
  CREATOR_CREATED: 'creator.created',
  CREATOR_UPDATED: 'creator.updated',
  CREATOR_PLATFORM_ACCOUNT_CREATED: 'creator.platform_account.created',
  CREATOR_PLATFORM_ACCOUNT_UPDATED: 'creator.platform_account.updated',
  CREATOR_PLATFORM_ACCOUNT_DELETED: 'creator.platform_account.deleted',
  CREATOR_SKILLS_UPDATED: 'creator.skills_updated',
  CREATOR_AVAILABILITY_UPDATED: 'creator.availability_updated',
  RECRUITER_CREATED: 'recruiter.created',
  RECRUITER_UPDATED: 'recruiter.updated',
} as const;

export const AUDIT_TARGET_TYPE = {
  INVITATION: 'invitation',
  MEMBERSHIP: 'membership',
  SESSION: 'session',
  PROFILE: 'profile',
  USER: 'user',
  LEAD: 'lead',
  CREATOR: 'creator',
  CREATOR_PLATFORM_ACCOUNT: 'creator_platform_account',
  RECRUITER: 'recruiter',
} as const;
