export const AUDIT_ACTION = {
  INVITATION_CREATED: 'invitation.created',
  INVITATION_ACCEPTED: 'invitation.accepted',
  INVITATION_REVOKED: 'invitation.revoked',
  MEMBERSHIP_UPDATED: 'membership.updated',
  SESSION_REVOKED: 'session.revoked',
  SESSIONS_REVOKED_OTHERS: 'sessions.revoked_others',
  PROFILE_UPDATED: 'profile.updated',
  ADMIN_USER_UPDATED: 'admin.user.updated',
  LEAD_CREATED: 'lead.created',
  LEAD_UPDATED: 'lead.updated',
  LEAD_DELETED: 'lead.deleted',
  LEAD_CLAIMED: 'lead.claimed',
  LEAD_REASSIGNED: 'lead.reassigned',
  LEAD_UNASSIGNED: 'lead.unassigned',
  LEAD_STATUS_CHANGED: 'lead.status_changed',
  LEAD_NOTE_ADDED: 'lead.note_added',
  LEAD_NOTE_UPDATED: 'lead.note_updated',
  LEAD_NOTE_DELETED: 'lead.note_deleted',
  LEAD_FOLLOWUP_UPDATED: 'lead.followup_updated',
  RECRUITER_CREATED: 'recruiter.created',
  RECRUITER_UPDATED: 'recruiter.updated',
} as const;

export const AUDIT_TARGET_TYPE = {
  INVITATION: 'invitation',
  MEMBERSHIP: 'membership',
  SESSION: 'session',
  PROFILE: 'profile',
  USER: 'user',
  LEAD: 'lead',
  RECRUITER: 'recruiter',
} as const;
