import {
  buildCampaignAnalytics,
  buildCreatorAnalytics,
  buildExecutiveOverview,
  buildExportCenter,
  buildIntelligenceDashboard,
  buildLiveAnalytics,
  buildRecruitingAnalytics,
} from '@/types/reporting-adapters';
import type { ManagerReportingWorkspace } from '@/types/reporting-workspace';

export function createMockReportingWorkspace(organizationId: string): ManagerReportingWorkspace {
  const mockCreators = Array.from({ length: 58 }, (_, index) => ({
    id: `creator_mock_${index + 1}`,
    organizationId,
    userId: `user_creator_${index + 1}`,
    displayName: `Creator ${index + 1}`,
    email: `creator${index + 1}@example.com`,
    country: index % 2 === 0 ? 'US' : 'CA',
    languages: ['en'],
    assignedRecruiterId: index % 3 === 0 ? 'user_recruiter_001' : null,
    status: index < 42 ? ('ACTIVE' as const) : ('SUSPENDED' as const),
    platformCount: (index % 5) + 1,
    createdAt: new Date(Date.now() - index * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  }));

  const mockCampaigns = [
    {
      id: 'camp_mock_001',
      organizationId,
      title: 'Summer Beauty Launch',
      description: 'Summer campaign',
      brandName: 'Glow Labs',
      campaignType: 'BRAND_DEAL' as const,
      status: 'ACTIVE' as const,
      budgetAmount: '5000.00',
      budgetCurrency: 'USD',
      startsAt: new Date().toISOString(),
      endsAt: new Date(Date.now() + 21 * 86400000).toISOString(),
      applicationDeadline: null,
      brief: {},
      requirements: {},
      metadata: {},
      createdByUserId: 'user_manager_001',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'camp_mock_002',
      organizationId,
      title: 'Holiday Live Marathon',
      description: 'Holiday campaign',
      brandName: 'Festive Co',
      campaignType: 'LIVE_STREAM' as const,
      status: 'COMPLETED' as const,
      budgetAmount: '12000.00',
      budgetCurrency: 'USD',
      startsAt: new Date(Date.now() - 60 * 86400000).toISOString(),
      endsAt: new Date(Date.now() - 30 * 86400000).toISOString(),
      applicationDeadline: null,
      brief: {},
      requirements: {},
      metadata: {},
      createdByUserId: 'user_manager_001',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  const mockLeads = [
    {
      id: 'lead_mock_001',
      organizationId,
      name: 'Alex Rivera',
      nickname: 'alexlive',
      email: 'alex@example.com',
      source: 'SOCIAL' as const,
      status: 'INTERESTED' as const,
      score: 82,
      assignedRecruiterId: 'user_recruiter_001',
      assignedAt: new Date().toISOString(),
      nextFollowUpAt: new Date().toISOString(),
      commissionPlan: 'STANDARD' as const,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'lead_mock_002',
      organizationId,
      name: 'Riley Nguyen',
      nickname: 'rileyn',
      email: 'riley@example.com',
      source: 'REFERRAL' as const,
      status: 'SIGNED' as const,
      score: 95,
      assignedRecruiterId: 'user_recruiter_001',
      assignedAt: new Date().toISOString(),
      nextFollowUpAt: null,
      commissionPlan: 'STANDARD' as const,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  const mockRecruiters = [
    {
      id: 'recruiter_profile_001',
      organizationId,
      userId: 'user_recruiter_001',
      displayName: 'Jordan Lee',
      nickname: 'Jordan',
      territory: 'West Coast',
      status: 'ACTIVE' as const,
      managerUserId: 'user_manager_001',
      commissionPlan: 'STANDARD' as const,
      monthlyLeadGoal: 40,
      monthlyCreatorGoal: 8,
    },
  ];

  const mockSessions = [
    {
      id: 'session_mock_001',
      organizationId,
      creatorProfileId: 'creator_mock_001',
      campaignId: null,
      title: 'Morning Live Shop',
      description: null,
      platform: 'TIKTOK' as const,
      platformSessionId: 'platform_session_001',
      status: 'LIVE' as const,
      startedAt: new Date().toISOString(),
      endedAt: null,
      scheduledStart: new Date().toISOString(),
      scheduledEnd: null,
      durationSeconds: 5400,
      totalViewers: 4200,
      peakViewers: 1800,
      totalGifts: 120,
      totalGiftValue: '1280.50',
      metadata: {},
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'session_mock_002',
      organizationId,
      creatorProfileId: 'creator_mock_002',
      campaignId: null,
      title: 'Creator Q&A',
      description: null,
      platform: 'TIKTOK' as const,
      platformSessionId: 'platform_session_002',
      status: 'ENDED' as const,
      startedAt: new Date(Date.now() - 86400000).toISOString(),
      endedAt: new Date(Date.now() - 82800000).toISOString(),
      scheduledStart: new Date(Date.now() - 86400000).toISOString(),
      scheduledEnd: new Date(Date.now() - 82800000).toISOString(),
      durationSeconds: 3600,
      totalViewers: 2100,
      peakViewers: 900,
      totalGifts: 55,
      totalGiftValue: '640.00',
      metadata: {},
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  return {
    organizationId,
    generatedAt: new Date().toISOString(),
    executiveOverview: buildExecutiveOverview({
      creators: mockCreators,
      campaigns: mockCampaigns,
      leads: mockLeads,
      liveSessions: mockSessions,
    }),
    creatorAnalytics: buildCreatorAnalytics(mockCreators),
    campaignAnalytics: buildCampaignAnalytics(mockCampaigns),
    recruitingAnalytics: buildRecruitingAnalytics(mockLeads, mockRecruiters),
    liveAnalytics: buildLiveAnalytics(mockSessions),
    intelligence: buildIntelligenceDashboard({
      creators: mockCreators,
      campaigns: mockCampaigns,
      leads: mockLeads,
      liveSessions: mockSessions,
    }),
    exportCenter: buildExportCenter(),
  };
}
